---
apiVersion: v1	
kind: Pod
metadata:
  name: mysql-pvc
  labels:
    app: mysql
spec:
  containers:
    - image: mysql:8
      name: mysql
      ports:
        - containerPort: 3306
      volumeMounts:
        - mountPath: var/lib/mysql       
          name: persistentvolumeclaim
  volumes:
    - name: persistentvolumeclaim
      persistentVolumeClaim:
        claimName: pvc-claim

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-claim
  labels:
    app: mysql
spec:
  accessModes: 
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp2



####  this manifest file create pod but not in running state, only in pending state
#### by using "efs"(this is create in cloud {aws}) this bug resolve.
          

  
