# storage class
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  labels: 
    app: nginx
  name: mystroageclass
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2


# pod
---
apiVersion: v1	
kind: Pod
metadata:
  name: mysql-pvc
  labels:
    app: mysql
spec:
  containers:
    - image: mysql:8
      name: mysql
      ports:
        - containerPort: 3306
      volumeMounts:
        - mountPath: var/lib/mysql       
          name: persistentvolume
  volumes:
    - name: persistentvolume
      persistentVolumeClaim:
        claimName: pvc-claim


# persistent volume claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-claim
  labels:
    app: mysql
spec:
  accessModes: 
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: mystroageclass





  


  
  
  
