apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob
spec:
  schedule: '* * * * *'
  jobTemplate:
    metadata:
      name: cronjob
    spec:
      template:
        metadata:
          name: cronjob
        spec:
          restartPolicy: OnFailure
          containers:
            - image: alpine
              name: alpine
              command:
                - sleep
                - 10s   