---
apiVersion: v1	
kind: Service
metadata:
  name: nginx-svc
  labels:
    app: nginx
spec:
  selector:
    app: nginx
  type: ClusterIP
  clusterIP: None
  ports:
    - name: nginx-svc
      port: 80
      targetPort: 80
      protocol: TCP
      
---
apiVersion: v1
kind: Pod
metadata:
  name: alpine-pod
spec:
  containers:
    - image: alpine
      name: alpine
      args:
        - sleep
        - 1d

---
apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: equivalent
  labels:
    app: nginx
spec:
  minReadySeconds: 2
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.23
          ports:
            - containerPort: 80                    