---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-stateful
  labels:
    app: mysql
spec:
  minReadySeconds: 1
  replicas: 3
  selector:
    matchLabels:
      app: mysql
  serviceName: mysql-svc   
  template:
    metadata:
      name: mysql-pod
      labels:
        app: mysql   
    spec:
      containers:
        - image: mysql:8
          name: mysql
          ports:
            - containerPort: 3306 
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: persistentvolume 
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: rootpassword
            - name: MYSQL_DATABASE
              value: database
            - name: MYSQL_USER
              value: user
            - name: MYSQL_PASSWORD
              value: password           
      volumes:
        - name: persistentvolume
          persistentVolumeClaim:
            claimName: pvc-claim

---
apiVersion: v1	
kind: Service
metadata:
  name: mysql-svc
  labels:
    app: mysql
spec:
  selector:
    app: mysql
  type: ClusterIP
  clusterIP: None
  ports:
    - name: mysql-svc
      port: 80
      targetPort: 80
      protocol: TCP 

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  labels: 
    app: nginx
  name: mystroageclass
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-claim
  labels:
    app: mysql
spec:
  accessModes: 
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: mystroageclass
