---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-stateful
  labels:
    app: mysql
spec:
  minReadySeconds: 1
  replicas: 3
  selector:
    matchLabels:
      app: mysql
  serviceName: mysql-svc   
  template:
    metadata:
      name: mysql-pod
      labels:
        app: mysql   
    spec:
      containers:
        - image: mysql:8
          name: mysql
          ports:
            - containerPort: 3306 
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: pvc-claim
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: rootpassword
            - name: MYSQL_DATABASE
              value: database
            - name: MYSQL_USER
              value: user
            - name: MYSQL_PASSWORD
              value: password
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        labels:
          app: mysql
        name: pvc-claim
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
        storageClassName: mystroageclass

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  labels: 
    app: nginx
  name: mystroageclass
provisioner: ebs.csi.aws.com
parameters:
  type: gp3           
                        
                 
      

