---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  labels:
    app: nginx
spec:
  selector: 
    app: nginx
  type: NodePort
  ports:
    - name: nginx-svc
      port: 81
      protocol: TCP  
      targetPort: 80