---
apiVersion: v1	
kind: Pod
metadata:
  name: affinity-pod
  labels:
    app: httpd
spec:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 1
          preference:
            matchExpressions:
              - key: purpose
                operator: In
                values: 
                  - testing
  containers:
    - name: nginx
      image: nginx:1.23
      ports:
        - containerPort: 80
