---
apiVersion: v1	
kind: Pod
metadata:
  name: paffinity
  labels:
    web: nginx-pod
  namespace: default
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - nginx
          topologyKey: "kubernetes.io/hostname"
  containers:
    - image: nginx
      name: nginx
      ports:
        - containerPort: 80   


---
apiVersion: v1	
kind: Pod
metadata:
  name: paffinity
  labels:
    web: nginx-pod
  namespace: default
spec:
  affinity:
    podAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - podAffinityTerm:
            labelSelector:
              matchExpressions:
                - key: app
                  operator: In
                  values:
                    - nginx
            topologyKey: "kubernetes.io/hostname" 
          weight: 1
  containers:
  - image: nginx
    name: nginx
    ports:
      - containerPort: 80   
        
  