---
apiVersion: v1
kind: Pod
metadata:
  name: toleration-pod
  labels:
    app: httpd
spec:
  containers:
    - image: httpd
      name: httpd
      ports:
        - containerPort: 80
  tolerations:
    - key: purpose
      operator: Equal
      value: testing
      effect: NoSchedule      
  