---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-rs 
  labels:
    app: nginx
spec:
  minReadySeconds: 2
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.23
          ports:
            - containerPort: 80      
          livenessProbe:
            failureThreshold: 1
            initialDelaySeconds: 1
            successThreshold: 1
            exec:
              command: 
                - sleep
                - 10MM
          readinessProbe:
            failureThreshold: 1
            initialDelaySeconds: 1
            successThreshold: 1
            exec:
              command: 
                - sleep
                - l0MM


---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  labels:
    app: nginx
spec:         
  selector:
    app: nginx 
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP                  
      name: nginx-svc