---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - pathType: /identity(/|$)(.*)
            path: Prefix
            backend:
              service:
                name: identity-svc
                port:
                  number: 80
          - pathType: /order(/|$)(.*)
            path: Prefix
            backend:
              service:
                name: order-svc
                port:
                  number: 80
          - pathType: /basket(/|$)(.*)
            path: Prefix
            backend:
              service:
                name: basket-svc
                port:
                  number: 80
          - pathType: /catalog(/|$)(.*)
            path: Prefix
            backend:
              service:
                name: catalog-svc
                port:
                  number: 80                                                      
  