---
apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: equivalent
  labels:
    app: jenkins
spec:
  minReadySeconds: 2
  replicas: 3
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
        - name: jenkins
          image: jenkins/jenkins:lts-jdk11
          ports:
            - containerPort: 8080 
        - name: alpine
          image: alpine:3
          args:
            - sleep
            - 1d
          
