---
apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  labels:
    app: mysql
    layer: db
spec:
  containers:
    - image: mysql:latest
      name: mysql
      ports:
        - containerPort: 3306
      volumeMounts:
        - name: mysql-vol
          mountPath: var/lib/mysql         
  volumes:
    - emptyDir:
        sizeLimit: 100Mi
      name: mysql-vol              
  