---
apiVersion: v1	
kind: Pod
metadata:
  name: mysql-pod
  labels:
    app: mysql
spec:
  containers:
    - image: mysql:8
      name: mysql
      ports:
        - containerPort: 3306
      env:
        - name: MYSQL_DATABASE
          value: database  
        - name: MYSQL_USER
          value: user
        - name: MYSQL_PASSWORD 
          value: password
        - name: MYSQL_ROOT_PASSWORD
          value: root-password  

       
