---
apiVersion: v1	
kind: Pod
metadata:
  name: mysql-pod
  labels:
    app: mysql
spec:
  containers:
    - image: mysql:8
      name: mysql
      ports:
        - containerPort: 3306
      env:
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: ConfigMap
              key: MYSQL_DATABASE 
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              name: ConfigMap
              key: MYSQL_USER 
