---
apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  labels: 
    app: mysql
spec:
  containers:
    - image: mysql:8
      name: mysql
      ports:
        - containerPort: 3306
      env: 
        - name: MYSQL_DATABASE
          value: ZGF0YWJhc2U=
        - name: MYSQL_USER
          value: dXNlcg==
        - name: MYSQL_PASSWORD
          value: cGFzc3dvcmQ=   